# Generated by Django 3.2.6 on 2021-08-28 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_subject_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
