# Generated by Django 3.2.6 on 2021-08-28 20:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0003_alter_subject_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('submission_time', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.subject')),
            ],
        ),
    ]
